import * as path from "node:path";
import * as vscode from "vscode";

const HTTP_METHOD_RE = /^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS|CONNECT|TRACE)\s+(.+)$/i;

type HurlEntry = {
  method: string;
  target: string;
  body: string;
};

export async function exportActiveHurlAsMarkdown(): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    void vscode.window.showWarningMessage("No active editor.");
    return;
  }
  if (editor.document.languageId !== "hurl" && !editor.document.fileName.endsWith(".hurl")) {
    void vscode.window.showWarningMessage("Active file is not a .hurl document.");
    return;
  }

  const source = editor.document.getText();
  const entries = parseEntries(source);
  if (entries.length === 0) {
    void vscode.window.showWarningMessage("No request entries found in current file.");
    return;
  }

  const markdown = renderMarkdown(editor.document.fileName, entries);
  const sourcePath = editor.document.uri.fsPath;
  const ext = path.extname(sourcePath);
  const outputPath = sourcePath.slice(0, sourcePath.length - ext.length) + ".md";
  const outputUri = vscode.Uri.file(outputPath);
  await vscode.workspace.fs.writeFile(outputUri, Buffer.from(markdown, "utf8"));
  const doc = await vscode.workspace.openTextDocument(outputUri);
  await vscode.window.showTextDocument(doc, { preview: false });
  void vscode.window.showInformationMessage(`Exported Markdown: ${outputPath}`);
}

function parseEntries(source: string): HurlEntry[] {
  const lines = source.split(/\r?\n/);
  const entries: HurlEntry[] = [];
  let currentMethod = "";
  let currentTarget = "";
  let currentLines: string[] = [];

  const flush = () => {
    if (!currentMethod || !currentTarget) {
      return;
    }
    entries.push({
      method: currentMethod,
      target: currentTarget,
      body: currentLines.join("\n").trim(),
    });
  };

  for (const line of lines) {
    const match = line.trim().match(HTTP_METHOD_RE);
    if (match) {
      flush();
      currentMethod = match[1].toUpperCase();
      currentTarget = match[2].trim();
      currentLines = [line];
      continue;
    }
    if (currentMethod) {
      currentLines.push(line);
    }
  }
  flush();
  return entries;
}

function renderMarkdown(fileName: string, entries: HurlEntry[]): string {
  const displayName = path.basename(fileName);
  const lines: string[] = [];
  lines.push(`# ${displayName}`);
  lines.push("");
  lines.push(`Generated by hurl-lsp at ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## Requests");
  lines.push("");
  for (let index = 0; index < entries.length; index += 1) {
    const entry = entries[index];
    lines.push(`### ${index + 1}. ${entry.method} ${entry.target}`);
    lines.push("");
    lines.push("```hurl");
    lines.push(entry.body);
    lines.push("```");
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}
