name: Publish Crates.io

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run cargo publish --dry-run only"
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Check package can be published
        run: cargo publish --package hurl-lsp --dry-run
      - name: Publish package
        if: ${{ inputs.dry_run != true }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --package hurl-lsp
